version: '3'

services:

  aqlabs:
    build: .
    ports:
      - "443:443"
    container_name: Aqlabs
    volumes:
      - /web.props:/app/application.properties
    command: ["java", "-jar", "app.jar", "--spring.config.location=/app/application.properties"]